### ISSUE TITLE
Review lab 9

### ISSUE THREAD

**Issue by AugustAasvaer** [fgiacome/compint#1]
The code is well-written and understandable.

Some code quality chances that could be done:
In the two-point crossover you could redefine d to not need the following conditional:
c = np.random.randint(0, len(pa))
d = np.random.randint(c, len(pa))

Given that the mutation probability is low, the convergence might be slow. perhaps testing with different values of p, could change that rate of convergence.

**Comment by fgiacome** [comment]
Thank you for the review.
